"""The kata's GIVEN suite — make solution.py pass every test, one at a time.

Do not edit this file: the grader runs its own copy of it.
"""
import pytest

from solution import add


def test_empty_string_is_zero():
    assert add("") == 0


def test_single_number():
    assert add("5") == 5


def test_two_numbers_comma_separated():
    assert add("1,2") == 3


def test_many_numbers():
    assert add("1,2,3,10") == 16


def test_newlines_count_as_separators_too():
    assert add("1\n2,3") == 6


def test_custom_delimiter_header():
    assert add("//;\n1;2") == 3


def test_negatives_are_rejected_and_all_listed():
    with pytest.raises(ValueError, match="negatives not allowed: -2, -4"):
        add("1,-2,3,-4")
